export const workoutActionTypes = {
  // List
  WORKOUT_LIST_REQUEST: "WORKOUT_LIST_REQUEST",
  WORKOUT_LIST_SUCCESS: "WORKOUT_LIST_SUCCESS",
  WORKOUT_LIST_FAILURE: "WORKOUT_LIST_FAILURE",

  // Add
  ADD_WORKOUT_REQUEST: "ADD_WORKOUT_REQUEST",
  ADD_WORKOUT_SUCCESS: "ADD_WORKOUT_SUCCESS",
  ADD_WORKOUT_FAILURE: "ADD_WORKOUT_FAILURE",
};
