export const workoutActionTypes = {
  // List
  WORKOUT_LIST_REQUEST: "WORKOUT_LIST_REQUEST",
  WORKOUT_LIST_SUCCESS: "WORKOUT_LIST_SUCCESS",
  WORKOUT_LIST_FAILURE: "WORKOUT_LIST_FAILURE",

  // Add
  ADD_WORKOUT_REQUEST: "ADD_WORKOUT_REQUEST",
  ADD_WORKOUT_SUCCESS: "ADD_WORKOUT_SUCCESS",
  ADD_WORKOUT_FAILURE: "ADD_WORKOUT_FAILURE",

  // Update
  UPDATE_WORKOUT_REQUEST: "UPDATE_WORKOUT_REQUEST",
  UPDATE_WORKOUT_SUCCESS: "UPDATE_WORKOUT_SUCCESS",
  UPDATE_WORKOUT_FAILURE: "UPDATE_WORKOUT_FAILURE",

  // Delete
  DELETE_WORKOUT_REQUEST: "DELETE_WORKOUT_REQUEST",
  DELETE_WORKOUT_SUCCESS: "DELETE_WORKOUT_SUCCESS",
  DELETE_WORKOUT_FAILURE: "DELETE_WORKOUT_FAILURE",
};
