export const workoutType = {
  // List
  WORKOUT_TYPE_LIST_REQUEST: "WORKOUT_TYPE_LIST_REQUEST",
  WORKOUT_TYPE_LIST_SUCCESS: "WORKOUT_TYPE_LIST_SUCCESS",
  WORKOUT_TYPE_LIST_FAILURE: "WORKOUT_TYPE_LIST_FAILURE",

  // Create
  ADD_WORKOUT_TYPE_REQUEST: "ADD_WORKOUT_TYPE_REQUEST",
  ADD_WORKOUT_TYPE_SUCCESS: "ADD_WORKOUT_TYPE_SUCCESS",
  ADD_WORKOUT_TYPE_FAILURE: "ADD_WORKOUT_TYPE_FAILURE",

  // Delete
  DELETE_WORKOUT_TYPE_REQUEST: "DELETE_WORKOUT_TYPE_REQUEST",
  DELETE_WORKOUT_TYPE_SUCCESS: "DELETE_WORKOUT_TYPE_SUCCESS",
  DELETE_WORKOUT_TYPE_FAILURE: "DELETE_WORKOUT_TYPE_FAILURE",

  // Update
  UPDATE_WORKOUT_TYPE_REQUEST: "UPDATE_WORKOUT_TYPE_REQUEST",
  UPDATE_WORKOUT_TYPE_SUCCESS: "UPDATE_WORKOUT_TYPE_SUCCESS",
  UPDATE_WORKOUT_TYPE_FAILURE: "UPDATE_WORKOUT_TYPE_FAILURE",
};
